---
sudo: false
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.2.0
  - 2.3.0
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 4.8.1"
matrix:
  exclude: []
